apiVersion: v1
kind: ConfigMap
metadata:
  name: mcp-hub-config
  labels:
    app: mcp-hub
    chart: mcp-hub
    release: mcp-hub
    heritage: Helm
data:
  mcp_settings.json: |-
{{ .Values.jsonconfig | nindent 4 }}
