apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mcphub.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "mcphub.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  config.json: |
{{ .Values.configJson | indent 4 }}
