apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mcphub.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mcphub.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mcphub.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mcphub.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: mcphub
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          volumeMounts:
            - name: app-persistent
              mountPath: /app
            - name: mcphub-config
              mountPath: /app/mcp_settings.json
              subPath: mcp_settings.json
      volumes:
        - name: app-persistent
          persistentVolumeClaim:
            claimName: {{ include "mcphub.fullname" . }}-app
        - name: mcphub-config
          configMap:
            name: {{ include "mcphub.fullname" . }}-config
