
image:
  repository: frdel/agent-zero-run
  tag: latest
  pullPolicy: Always

resources:
  limits:
    cpu: "4"
    memory: "8Gi"
  requests:
    cpu: "2"
    memory: "4Gi"

# IMPORTANT: To ensure persistent data is kept after helm uninstall, use a StorageClass with reclaimPolicy: Retain.
# For example:
# ---
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: retain-local-path
# provisioner: rancher.io/local-path
# reclaimPolicy: Retain
# volumeBindingMode: WaitForFirstConsumer
# ---
# Then set persistence.storageClass: retain-local-path
persistence:
  enabled: true
  storageClass: local-path
  size: 2Gi    

env:
  - name: API_KEY_OPENAI
    value: "sk-..."

