image:
  repository: samanhappy/mcphub
  tag: latest
  pullPolicy: IfNotPresent
service:
  enabled: true
  port: 3000
  type: ClusterIP
configJson: |
  {
    "mcpServers": {
      "memory": {
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-memory"]
      },
      "time": {
        "command": "uvx",
        "args": ["mcp-server-time", "--local-timezone=America/New_York"]
      }
    }
  }
container:
  command:
    - mcphub
  args:
    - --config=/app/mcp_settings.json

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 5Gi
  storageClass: local-path

