image:
  repository: node
  tag: 20-slim
service:
  type: ClusterIP
  port: 8000
jsonconfig: |
  {
    "mcpServers": {
      "memory": {
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-memory"]
      },
      "time": {
        "command": "uvx",
        "args": ["mcp-server-time"],
        "env": {"TIMEZONE": "Europe/Berlin"}
      },
      "context7": {
        "command": "npx",
        "args": ["-y", "@upstash/context7-mcp"]
      },
      "mcp-cypher": {
        "command": "uvx",
        "args": ["mcp-neo4j-cypher@latest"],
        "env": {
          "NEO4J_SERVER_URL": "bolt://neo4j.neo4j:7687",
          "NEO4J_USERNAME": "neo4j",
          "NEO4J_PASSWORD": "demodemo"
        }
      },
      "mcp-data-modeling": {
        "command": "uvx",
        "args": ["mcp-neo4j-data-modeling@latest"]
      }
    }
  }
